### ISSUE TITLE
Licensing conflict

### ISSUE THREAD

**Issue by ghisvail** [bayespy/bayespy#100]
The file `bayespy/inference/vmp/nodes/logistic.py` is licensed under the GPL version 3 whereas the package is distributed under the MIT license. If this is an omission from a relicensing effort, please closely inspect the code base and correct such errors. Otherwise, the full package should be licensed under the GPL-3 as well.

Thanks,
Ghis

**Comment by jluttine** [comment]
Thanks for pointing it out. It's just an omission from a relicensing effort. I'll fix that immediately.

**Comment by ghisvail** [comment]
Would you consider tagging version 0.5.8 and uploading a new release to PyPI (still at 0.5.6) once this is fixed? That would be help my packaging effort for Debian.

**Comment by jluttine** [comment]
Yes, I'll do these fixes in a few hours.

**Comment by jluttine** [comment]
This is now fixed in 0.5.8 available at PyPI.

**Comment by ghisvail** [comment]
Nice, thanks
