### ISSUE TITLE
Extended Marble Example

### ISSUE THREAD

**Issue by dar326** [bayespy/bayespy#109]
Hello,

In an attempt to use BayesPy in a research project that I am working on, I wanted to get a toy problem working which shares structural characteristics to my actual problem. I decided to build this example on top of the marble example in the BayesPy documentation: http://www.bayespy.org/examples/multinomial.html.

The backstory for this problem is silly but simplifies some details that are unimportant for the model that I want to build. But here goes:

There are many bags of colored marbles from countries throughout the world. Each bag contains different (but known) amounts of each color. We also know the country (and, therefore, continent of origin of each bag). A marble aficionado, Kathleen, has been collecting these bags of marbles and meticulously labeling them for many years in a large ditch that use to be a pond until an environmental incident caused all of the water in the pond to evaporate.

A recent oil drilling expedition causes oil to seep into the ditch containing the marbles, carrying away a large portion of the bags and covering the remaining bags in oil. To Kathleen's dismay, the marble collector learns that this is a very concentrated type of oil with chemical properties that cause the labels on the bags of marbles to be unreadable.

With Kathleen's years of work in jeopardy she wants to know which marbles are still in her collection. Unfortunately, the same chemical properties which removed the bag labels is toxic to human skin so she cannot recover the bags on her own. Hearing about her story on the news, a brilliant engineer named Marcy has developed a machine which can maneuver on the surface of the oil pond. The movements of this machine are randomly determined so that the machine stays on the surface of the pond but is able to explore most areas of the pond. It has an extendable arm that can reach the bottom of the pond. This extendable arm can open one bag at a time and remove a fixed number (_n_trials_) of marbles from the bag and report the color of each of these marbles. However, there is a limit to the number (_n_obs_) of times this bag-selection/marble-counting exercise can be performed before the machine needs to be removed from the toxic oil.

Kathleen wants to know which bags of marbles are still in her collection and the quantity of each bag. She would also like to know higher level information about the distribution of countries and continents of the marble bags in her collection.

### Data generation

```
n_colors = 7  # number of possible colors
n_bags = 5    # number of bags
n_trials = 20 # number of draws from each bag
n_obs = 2000 # number of times the draw experiment is repeated
n_continents = 3
n_countries = 5
min_marble_count = 1000
max_marble_count = 10000
```

```
# probability of each country being on particular continent
p_continents = bp.nodes.Dirichlet(n_continents * [0.5], name="p_continents").random()
continents = bp.nodes.Categorical(p_continents, name="continents", plates=(n_obs,))
```
```
bpplt.hinton(p_continents)
bpplt.pyplot.title("Original distribution of continents")
```
![image](https://user-images.githubusercontent.com/18688128/36513570-40541d1e-173e-11e8-8d18-c73b72113110.png)

```
# probability that an observed collection of marbles comes from a particular country
p_countries = bp.nodes.Dirichlet(np.random.rand(n_continents, 1, n_countries), name="p_countries").random()
countries = bp.nodes.Mixture(continents, bp.nodes.Categorical, p_countries, name="continents", cluster_plate=-2)
```

```
bpplt.hinton(p_countries)
bpplt.pyplot.title("Original distribution of countries")
```
![image](https://user-images.githubusercontent.com/18688128/36513593-6b1b6eb2-173e-11e8-87cf-45394c239d2d.png)

```
# probability of each color in bag
p_bags = bp.nodes.Dirichlet(np.random.rand(n_countries, 1, n_bags), name="p_bags").random()
bags = bp.nodes.Mixture(countries, bp.nodes.Categorical, p_bags, name="countries", cluster_plate=-2)
```

```
bpplt.hinton(p_bags)
bpplt.pyplot.title("Original distribution of bags")
```
![image](https://user-images.githubusercontent.com/18688128/36513976-34cd1c1e-1740-11e8-9225-acc030510869.png)

```
# known marble color distributions in bags
bag_color_dist = np.zeros((n_bags, 1, n_colors))
for i in range(n_bags):
    # randomly specify the number of marbles in each bag
    bag_sizes[i] = np.random.randint(min_marble_count, max_marble_count)
    probs = np.random.rand(n_colors)
    bag_color_dist[i,0,:] = np.random.multinomial(bag_sizes[i], probs/sum(probs))
```

```
# use the bag counts with an uninformative prior (alpha = 1) to create a Dirichlet distribution 
# representing the known bag distributions
draw_count = [n_trials]*n_obs
p_colors = bp.nodes.Dirichlet(bag_color_dist+1, name="p_colors").random()
marbles = bp.nodes.Mixture(bags, bp.nodes.Multinomial, draw_count, p_colors, name="colors", cluster_plate=-2).random()
```

```
bpplt.hinton(p_colors)
bpplt.pyplot.title("Distribution of marble colors in bags")
```
![image](https://user-images.githubusercontent.com/18688128/36514016-63020c34-1740-11e8-9bb0-ccbaf8ef0572.png)

### Problem Inference

```
theta_continents = bp.nodes.Dirichlet(n_continents * [0.5], name="theta_continents")
X_continents = bp.nodes.Categorical(theta_continents, name="X_continents", plates=(n_obs,))
theta_countries = bp.nodes.Dirichlet(np.random.rand(n_continents, 1, n_countries), name="theta_countries")
X_countries = bp.nodes.Mixture(X_continents, bp.nodes.Categorical, theta_countries, name="X_countries", cluster_plate=-2)
theta_bags = bp.nodes.Dirichlet(np.random.rand(n_countries, 1, n_bags), name="theta_bags")
X_bags = bp.nodes.Mixture(X_countries, bp.nodes.Categorical, theta_bags, name="X_bags", cluster_plate=-2)
Y = bp.nodes.Mixture(X_bags, bp.nodes.Multinomial, draw_count, p_colors, name="obs_colors", cluster_plate=-2)

Q = bp.inference.VB(theta_continents, X_continents, theta_countries, X_countries, theta_bags, X_bags, Y)

theta_bags.initialize_from_random()
theta_countries.initialize_from_random()

Y.observe(marbles)
```

```
Q.update(repeat=1000)
Iteration 1: loglike=-3.308110e+04 (0.011 seconds)
Iteration 2: loglike=-2.607901e+04 (0.013 seconds)
Iteration 3: loglike=-1.993212e+04 (0.014 seconds)
Iteration 4: loglike=-1.919837e+04 (0.019 seconds)
Iteration 5: loglike=-1.914465e+04 (0.018 seconds)
Iteration 6: loglike=-1.913860e+04 (0.028 seconds)
Iteration 7: loglike=-1.913744e+04 (0.021 seconds)
Iteration 8: loglike=-1.913719e+04 (0.013 seconds)
Iteration 9: loglike=-1.913712e+04 (0.011 seconds)
Converged at iteration 9.
```

```
bpplt.hinton(theta_continents)
bpplt.pyplot.title("Learned distribution of continents")
bpplt.pyplot.show()
```
![image](https://user-images.githubusercontent.com/18688128/36514140-18fcf5bc-1741-11e8-85b6-76c2f33ab12f.png)

```
p = np.exp(theta_countries.get_moments()[0])
# Explicit broadcasting
p = p * np.ones(theta_countries.plates+(1,))
bpplt._hinton(p[:,0,:], vmax=1.0)
bpplt.pyplot.title("Learned distribution of countries")
bpplt.pyplot.show()
```
![image](https://user-images.githubusercontent.com/18688128/36514194-5841c72a-1741-11e8-83fa-06a2a580fea4.png)

```
p = np.exp(theta_bags.get_moments()[0])
# Explicit broadcasting
p = p * np.ones(theta_bags.plates+(1,))
bpplt._hinton(p[:,0,:], vmax=1.0)
bpplt.pyplot.title("Learned distribution of bags")
bpplt.pyplot.show()
```
![image](https://user-images.githubusercontent.com/18688128/36514158-334124ac-1741-11e8-95af-18310776c4db.png)

I chose small parameter values at the top of my script to make sure that the Hinton plots can be reasonably visualized. However, before I start to really experiment with this model, I wanted to make sure that I am running the inference properly. In particular, I have noticed that in some of the examples the order in which the random variables are specified when creating the VB object (_Q_) can be important as well as the random initialization of values in some of these variables. 

Am I setting up my model properly in this regard?

Thanks,
Darryl

**Comment by jluttine** [comment]
Didn't check whether the model is set up properly or not, but just answering one question: Yes, the order in which you provide nodes to the model creation (the Q object), is the default update order. So, when you run Q.update(), you update nodes in that order. You can specify any other order and/or subset to the update method if you want. The update order is important in some cases, at the very beginning. Typically, you initialize some nodes and update first the other variables based on those initializations. Also, typically, I'd learn first the nodes that are closer to the observed nodes.
