### ISSUE TITLE
How to extract posterior over latent states from CategoricalMarkovChain

### ISSUE THREAD

**Issue by RylanSchaeffer** [bayespy/bayespy#119]
How does one extract the posterior over latent states from `CategoricalMarkovChain`? The object has an array with shape `(length of chain, number of latent variables, number of latent variables)`. I don't see a clear answer in the documentation (https://www.bayespy.org/user_api/generated/generated/bayespy.nodes.CategoricalMarkovChain.html) or the example (https://www.bayespy.org/examples/hmm.html).

This seems so simple. I must be missing something obvious.

**Comment by RylanSchaeffer** [comment]
I found my answer:

```
from bayespy.inference.vmp.nodes.categorical_markov_chain import CategoricalMarkovChainToCategorical

latents_posterior = CategoricalMarkovChainToCategorical(latents).get_moments()[0]

```

**Comment by jluttine** [comment]
Ah, sorry for the late response, but glad you found a solution. I wrote a bit longer response here: https://github.com/bayespy/bayespy/issues/28#issuecomment-636459097
