### ISSUE TITLE
Remove deprecated time.clock() call

### ISSUE THREAD

**Issue by micmicqb** [bayespy/bayespy#120]
The method `Q.update()` throws the following error in Python3.8:

> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-121-c245650290aa> in <module>
> ----> 1 amalthea_vi.Q.update(repeat=100, tol=1e-4)
> 
> /usr/local/anaconda3/envs/amalthea/lib/python3.8/site-packages/bayespy/inference/vmp/vmp.py in update(self, repeat, plot, tol, verbose, tqdm, *nodes)
>     161         while repeat is None or i < repeat:
>     162 
> --> 163             t = time.clock()
>     164 
>     165             # Update nodes
> 
> AttributeError: module 'time' has no attribute 'clock'
> ```

This is because the function `time.clock()` has been deprecated. See here: https://stackoverflow.com/a/58569410/13157943.

**Comment by jluttine** [comment]
This was fixed by https://github.com/bayespy/bayespy/pull/121 in the latest release. Thanks! :+1:
