### ISSUE TITLE
Errors in the demos

### ISSUE THREAD

**Issue by ztanml** [bayespy/bayespy#128]
Some demos in the 0.5.24 cannot successfully run, indicating potential bugs in the code. For example:
- collapsed_cg.py: No automatic conversion from CategoricalMoments to CategoricalMoments with different number of categories
- lssm_sd.py: No conversion defined from GaussianMoments to CategoricalMoments
- lssm_tvd.py: 'GaussianMarkovChain' object has no attribute '_convert'

**Comment by jluttine** [comment]
Thanks for reporting! Indeed, there were a few bugs. They should be fixed now in develop, I hope. I'll make a new release.
