### ISSUE TITLE
Equations not showing in docs

### ISSUE THREAD

**Issue by Stevod** [bayespy/bayespy#130]
In readthedocs, equations are showing as the underlying markup, not rendering as the math equations as they should. Makes it very difficult to understand what is going on, in what is a very powerful and sophisticated library but which does need good docs .

**Comment by jluttine** [comment]
Thanks for reporting! :+1: Yeah, this needs to be fixed. I'll try to find some time soon.

**Comment by jluttine** [comment]
I fixed this now but unfortunately the domain bayespy.org points to wrong content for some reason (trying to figure this out with GitHub support). But the docs are also available at https://bayespy.github.io/bayespy/ 

EDIT: GitHub fixed the GH pages issue, so bayespy.org is pointing to the correct content now.
