### ISSUE TITLE
Pip install fails with Python 3.12

### ISSUE THREAD

**Issue by anttimc** [bayespy/bayespy#131]
Running pip install with Python 3.12 fails in the following error in versioneer.py
```
96.67         File "/tmp/pip-install-xmkiing1/bayespy_f5279fc541f44da081b2f825ee8dc1a1/versioneer.py", line 412, in get_config_from_root
96.67           parser = configparser.SafeConfigParser()
96.67                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
96.67       AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```
According to the release summary https://docs.python.org/3/whatsnew/3.12.html#configparser
`SafeConfigParser` has been renamed to `ConfigParser`

**Comment by anttimc** [comment]
After reading a few similar github issues, I saw that `SafeConfigParser` was deprecated already in Python 3.2 and renamed to `ConfigParser`. So just updating the really old versioneer.py version might help here.

**Comment by jluttine** [comment]
Thanks! Versioneer updated in 0.6.2. I hope it fixes the issue.
