### ISSUE TITLE
Switch license from GPL to MIT?

### ISSUE THREAD

**Issue by jluttine** [bayespy/bayespy#16]
I am considering switching the license from GPLv3 to MIT. 

"the most important two predictors of success for a software project are the number of users and the number of contributors. Because of the restrictions and subtle legal issues involved with GPL licenses, many for-profit companies will not touch GPL-licensed code, even if they are happy to contribute their changes back to the community. A BSD license, on the other hand, removes these restrictions: Hunter mentions several specific examples of vital industry partnership in the case of matplotlib. He argues that in general, a good BSD-licensed project will, by virtue of opening itself to the contribution of private companies, greatly grow its two greatest assets: its user-base and its developer-base."

For more detailed arguments, see:
https://web.stanford.edu/~vcs/talks/VictoriaStoddenIPSC2010.pdf
www.astrobetter.com/blog/2014/03/10/the-whys-and-hows-of-licensing-scientific-code/

If anyone wants to comment on this, please do so quickly, because I'm planning to switch the license this week.

**Comment by pypingou** [comment]
You need to get the agreement of every person that has contributed to the project to change the license, so all the (3) contributors listed at: https://github.com/bayespy/bayespy/graphs/contributors

**Comment by jluttine** [comment]
Thanks for the comment! I have a private/personal agreement from Hannu Hartikainen. The contributions of Laura Dietz were for a sub-module that is not a part of BayesPy anymore, thus it doesn't matter. Thus, everything should be ok. Maybe @dancek (Hannu Hartikainen) could also provide a public agreement here?

**Comment by dancek** [comment]
Yes, I am giving my permission to publish all my contributions to `bayespy` under the MIT license.

**Comment by pypingou** [comment]
Then you should be good to go :)
