### ISSUE TITLE
Example code raising errors...

### ISSUE THREAD

**Issue by nickfyson** [bayespy/bayespy#17]
Not sure why, but it seems one of the code examples raises an error. From the docstring in bernoulli.py...

```python
from bayespy.nodes import Bernoulli, Beta
p = Beta([1e-3, 1e-3])
z = Bernoulli(p, plates=(10,))
z.observe([0, 1, 1, 1, 0, 1, 1, 1, 0, 1])
p.update()
import bayespy.plot as bpplt
import numpy as np
bpplt.pdf(p, np.linspace(0, 1, num=100))
```

Running this raises the following...

```
Traceback (most recent call last):
  File "bayespy_example.py", line 8, in <module>
    bpplt.pdf(p, np.linspace(0, 1, num=100))
  File "/path/to/module/bayespy/bayespy/plot.py", line 190, in pdf
    lpdf = Z.logpdf(x)
  File "/path/to/module/bayespy/bayespy/inference/vmp/nodes/expfamily.py", line 500, in logpdf
    (u, f) = self._distribution.compute_fixed_moments_and_f(X, mask=mask)
  File "/path/to/module/bayespy/bayespy/inference/vmp/nodes/beta.py", line 85, in compute_fixed_moments_and_f
    return super().compute_fixed_moments_and_f(p, mask=mask)
  File "/path/to/module/bayespy/bayespy/inference/vmp/nodes/dirichlet.py", line 152, in compute_fixed_moments_and_f
    p = np.asanyarray(p)
UnboundLocalError: local variable 'p' referenced before assignment
```

**Comment by nickfyson** [comment]
Just renaming the argument in `compute_fixed_moments_and_f` to `p` instead of `x` resulted in a different error, and I'm afraid I didn't dig any deeper than that... :-S

**Comment by jluttine** [comment]
Thanks a lot for the report! I noticed that this example in the docstring was not covered by unit tests so the example hasn't helped me notice the bug in Dirichlet. I now modified the docstring so that it is used by the unit tests so this would raise a unit test error in the future. I also fixed the actual bug in the Dirichlet node that you reported. Thanks!
