### ISSUE TITLE
Rotation for contant A

### ISSUE THREAD

**Issue by colaresi** [bayespy/bayespy#18]
Thank you for your work on bayespy, I have found it an extremely useful resource. I am trying to speed up inference for a hierarchical state space model with a constant A (specifically an identity matrix). 
I saw that this case was not yet implemented (and noted with a "TODO" in the docs and code) for the parameter expansion by rotation, but was wondering if there was a quick way for me to implement this simplest of cases: 
```python
A = np.tile(np.identity(D),(I,1,1,1)) 
```
where I is simply the number of independent units I observe (and thus y is M x I x N). D is the number of latent dimensions as in your example.
Without the transformation/rotations, I can set everything up (which is thanks to your documentation), but the inference engine proceeds very slowly (as you write).
Thank you for any help you could provide.

**Comment by jluttine** [comment]
Thanks for the message, glad to hear that BayesPy has been useful. About the rotation: there might be an alternative solution.

First, the idea in general: You can give your latent variables as flexible priors as possible, for instance, Gaussian with Wishart instead of ARD. That way, the Wishart distribution will adjust to the rotation and there is no need to perform rotation. For instance, one classical way to construct PCA is:
```
X = GaussianARD(0, 1, shape=(D,), plates=(1,N))
alpha = Gamma (1e-3, 1e-3, plates=(D,))
C = GaussianARD(0, alpha, shape=(D,), plates=(M,1))
F = SumMultiply('i,i->', X, C)
# and so on..
```
This needs rotation tricks to converge quickly. However, if you construct it like:
```
Lambda_X = Wishart(D, 1e-3 * np.identity(D))
X = Gaussian(np.zeros(D), Lambda_X, plates=(1,N))
Lambda_C = Wishart(D, 1e-3 * np.identity(D))
C = Gaussian(np.zeros(D), Lambda_C, plates=(M,1))
F = SumMultiply('i,i->', X, C)
# and so on..
```
then you get fast convergence without any rotations because the hyperparameters `Lambda_X` and `Lambda_C` provide flexibility. The model is slightly different than with the ARD prior, but I think it makes no difference when you have much larger data dimensions `M` and `N` than latent space dimensionality `D`. This was a rather general idea.

So, back to your problem. The slow convergence is partly due to the fixed rotation in the priors. So if possible, you might consider relaxing this fixed rotation as much as possible. This could be achieved by:

 * use Wishart precision (not ARD) for the loading matrix `C`
 * learn the innovation noise variances

I'm not sure if you have already done these or if they help sufficiently. But at least, if possible to use, it's very simple to try. When you need to use the rotation tricks, it becomes a bit more complex. So I'd try this first, and if it's not fast enough, then consider implementing the rotations for the constant state dynamics matrix. The prior for the state variables `X` would look something like:
```
rho = Gamma(1e-3, 1e-3, plates=(I, 1, D))
X = GaussianMarkovChain(np.zeros(D), 1e-3*np.identity(D), A, rho, n=N, plates=(I,), name='X')
```
and the prior for the loading matrix `C`:
```
Lambda_C = Wishart(D, 1e-3 * np.identity(D), plates=(1,I,1))
C = Gaussian(np.zeros(D), Lambda_C, plates=(M,I,1))
```
Here, I assumed that you use different loading matrix `C` for each process. If you don't want that, just replace `I` with `1`. I quickly sketched this, so I hope there are no errors. And you may need to work on the details. Anyway, please let me know if this is something you can try and whether it helps or not.

**Comment by colaresi** [comment]
Thank you very much. That is extremely helpful. The combination of learning the noise variance and the Wishart prior on C did speed up convergence (I am just using a model with a common C for each component). A short example of what I did is below, along with the output from 10 updates for each.

```Python
import numpy as np
from bayespy.nodes import GaussianARD, GaussianMarkovChain, Gaussian, Wishart, Gamma, Dot
from bayespy.inference import VB
from bayespy.inference.vmp import transformations
import bayespy.plot as bpplt

np.random.seed(seed=123456789)

def MakeLIPSimData(M,I,N,D):
   a = np.identity(D)
   c = np.random.randn(M,D)
   x = np.empty((N,I,D))
   y = np.empty((M,I,N))
   f = np.empty((M,I,N))
   for i in range(I):
      x[0,i] = 5*np.random.randn(D)
      f[:,i,0] = np.dot(c,x[0,i])
      y[:,i,0] = f[:,i,0] + 3*np.random.randn(M)
      for n in range(N-1):
         x[n+1,i] = np.dot(a,x[n,i]) + np.tile(5,D)*np.random.randn(D)
         f[:,i,n+1] = np.dot(c,x[n+1,i])
         y[:,i,n+1] = f[:,i,n+1] + 3*np.random.randn(M)
   return([y,c,x])


def LIP(D, arraY,maxiter=100):
   #D      : Number of latent dimensions, must be int
   #arraY  : the observed data, must be a numpy array; should have three dimension (M x I x N), in that order (M is num obs per time slice, I is num of individual, N is time)
   #maxiter: max number of iterations 
   M,I,N = arraY.shape
   D = D
   #State dynamics are set to random walk
   A = np.tile(np.identity(D),(I,1,1,1))
   #The states, 
   #the state noise precision is given a Gamma prior 
   rho = Gamma(1e-3, 1e-3, plates=(I, 1, D), name='rho')
   #X, states with precision. 
   X = GaussianMarkovChain(np.zeros((I,D)), 1e-3*np.tile(np.identity(D),(I,1,1)), A, rho, n=N, name='X')
   #C is the loading matrix, Gaussian prior, with Wishart prior on precision
   #Same C for everyone
   #Trying Wishart prior 
   Lambda_C = Wishart(D, 1e-3*np.identity(D),plates=(1,1,1), name='Lambda_C')
   C = Gaussian(np.zeros(D), Lambda_C, plates=(M,1,1), name='C')
   #Y is noisy version of F.
   F = Dot(C,X, name='F')
   #kick-off C, so we don't get stuck at zero
   C.initialize_from_random()
   #measurement noise precision
   tau = Gamma(1e-5,1e-5,name='tau')
   #draw Y, from F and tau
   Y = GaussianARD(F,tau,name='Y')
   #Observe Y, which is arraY
   Y.observe(arraY)
   #inference, X before C
   Q = VB(X, C, rho, Lambda_C, tau, Y)
   #update
   Q.update(repeat=maxiter)
   return({'rho':rho,'X':X,'C':C,'Lambda_C':Lambda_C,'tau':tau,'Y':Y,'Q':Q})

def LIPNormalized(D, arraY,maxiter=100):
   #Unlike LIP, here the unobserved precision for the noise is given a fixed identity matrix; 
   #D      : Number of latent dimensions, must be int
   #arraY  : the observed data, must be a numpy array; should have three dimension 
   #maxiter: max number of iterations 
   M,I,N = arraY.shape
   D = D
   #State dynamics are set to random walk
   A = np.tile(np.identity(D),(I,1,1,1))
   #The states, the state noise precision is given a Gamma prior 
   rho = np.ones((I,1,D))
   #X, states with precision. 
   X = GaussianMarkovChain(np.zeros((I,D)), 1e-3*np.tile(np.identity(D),(I,1,1)), A, rho, n=N, name='X')
   #C is the loading matrix, precision has Gamma prior
   gamma = Gamma(1e-5,1e-5, plates=(D,), name='gamma')
   C = GaussianARD(np.zeros(D), gamma, shape=(D,), plates=(M,1,1), name='C')
   #Y is noisy version of F.
   F = Dot(C,X, name='F')
   #kick-off C, so we don't get stuck at zero
   C.initialize_from_random()
   #measurement noise
   tau = Gamma(1e-5,1e-5,name='tau')
   #draw Y, from F and tau
   Y = GaussianARD(F,tau,name='Y')
   #Observe Y, which is arraY
   Y.observe(arraY)
   #inference, X before C
   #no need to update rho here
   Q = VB(X, C, gamma, tau, Y)
   #update
   Q.update(repeat=maxiter)
   #rho is not returned since it is simply the identitity matrix
   return({'X':X,'C':C,'gamma':gamma,'tau':tau,'Y':Y,'Q':Q})

#Simulate Data
SimData = MakeLIPSimData(M=1000,I=8,N=4000,D=2)

#Run first Model
NormResults = LIPNormalized(D=10, arraY=SimData[0],maxiter=10)

#Other (with Wishart prior)
OtherResults = LIP(D=10,arraY=SimData[0],maxiter=10)

```

and the results up to 10 iterations:

```
... NormResults = LIPNormalized(D=10, arraY=SimData[0],maxiter=10)
Iteration 1: loglike=-8.385317e+07 (33.946 seconds)
Iteration 2: loglike=-8.124931e+07 (33.672 seconds)
Iteration 3: loglike=-8.111292e+07 (33.656 seconds)
Iteration 4: loglike=-8.101814e+07 (33.696 seconds)
Iteration 5: loglike=-8.096581e+07 (33.886 seconds)
Iteration 6: loglike=-8.093951e+07 (33.886 seconds)
Iteration 7: loglike=-8.092525e+07 (34.197 seconds)
Iteration 8: loglike=-8.091669e+07 (33.611 seconds)
Iteration 9: loglike=-8.091121e+07 (34.259 seconds)
Iteration 10: loglike=-8.090755e+07 (33.615 seconds)

... OtherResults = LIP(D=10,arraY=SimData[0],maxiter=10)
Iteration 1: loglike=-1.060418e+08 (33.700 seconds)
Iteration 2: loglike=-8.100705e+07 (33.632 seconds)
Iteration 3: loglike=-8.088087e+07 (33.603 seconds)
Iteration 4: loglike=-8.086045e+07 (33.583 seconds)
Iteration 5: loglike=-8.085477e+07 (33.762 seconds)
Iteration 6: loglike=-8.085199e+07 (33.771 seconds)
Iteration 7: loglike=-8.085037e+07 (34.075 seconds)
Iteration 8: loglike=-8.084934e+07 (34.003 seconds)
Iteration 9: loglike=-8.084865e+07 (33.986 seconds)
Converged at iteration 9.


```

**Comment by jluttine** [comment]
Ok, great! :) Feel free to ask if you have further questions about this.

**Comment by colaresi** [comment]
Hi. Thank you again for BayesPy. 
I do have a specific question that I hope you can help me with. I was re-running the exact code I wrote about previously (referred to in closed issue #18 here) using BayesPy v0.5.1 instead  of v0.3.1 and now get an error. When I pop back to my old virtual environment, I do not have a problem. I see that some of the functions in linalg.py have change. I am guessing is has something to do with the way I set-up the plates and the broadcasting rules used? Do you have any advice for how I can set up the GaussianMarkovChain node to work with this example with current versions of BayesPy? I am happy to provide any additional details if they might help. Thank you in advance.

Here is the model set-up (in the LIP function) and the error when run.

def LIP(D, arraY,maxiter=100):
   #D      : Number of latent dimensions, must be int
   #arraY  : the observed data, must be a numpy array; should have three dimension (Words x Countries x Time), in that order
   #maxiter: max number of iterations 
   M,I,N = arraY.shape
   D = D
   #State dynamics are set to random walk
   A = np.tile(np.identity(D),(I,1,1,1))
   #The states, the state noise precision is given a Gamma prior 
   rho = Gamma(1e-3, 1e-3, plates=(I, 1, D), name='rho')
   #X, states with precision. 
   X = GaussianMarkovChain(np.zeros((I,D)), 1e-3*np.tile(np.identity(D),(I,1,1)), A, rho, n=N, name='X')
   #C is the loading matrix, precision has Gamma prior
   #gamma = Gamma(1e-5,1e-5, plates=(D,), name='gamma')
   #Same C for everyone
   #Try Wishart prior 
   Lambda_C = Wishart(D, 1e-3*np.identity(D),plates=(1,1,1), name='Lambda_C')
   C = Gaussian(np.zeros(D), Lambda_C, plates=(M,1,1), name='C')
   #Y is noisy version of F.
   F = Dot(C,X, name='F')
   #kick-off C, so we don't get stuck at zero
   C.initialize_from_random()
   #measurement noise
   tau = Gamma(1e-5,1e-5,name='tau')
   #draw Y, from F and tau
   Y = GaussianARD(F,tau,name='Y')
   #Observe Y, which is arraY
   Y.observe(arraY)
   #inference, X before C
   Q = VB(X, C, rho, Lambda_C, tau, Y)
   #update
   Q.update(repeat=maxiter)
   return({'rho':rho,'X':X,'C':C,'Lambda_C':Lambda_C,'tau':tau,'Y':Y,'Q':Q})


>>> from bayespy.nodes import GaussianARD, GaussianMarkovChain, Gaussian, Wishart, Gamma, Dot
>>> from bayespy.inference import VB
>>> from bayespy.inference.vmp import transformations
>>> import bayespy.plot as bpplt
>>> 
>>> from LIP import MakeLIPSimData, LIPNormalized, LIP, MakeLIPSArray, LoadDataYFromCSV
>>> 
>>> ResultsLIP = LIP(2,ewc_final)
Traceback (most recent call last):
  File "/Users/michaelcolaresi/anaconda/envs/myBayesPyDot51/lib/python3.5/site-packages/bayespy/utils/linalg.py", line 49, in chol
    U[i] = linalg.cho_factor(C[i])[0]
  File "/Users/michaelcolaresi/anaconda/envs/myBayesPyDot51/lib/python3.5/site-packages/scipy/linalg/decomp_cholesky.py", line 132, in cho_factor
    check_finite=check_finite)
  File "/Users/michaelcolaresi/anaconda/envs/myBayesPyDot51/lib/python3.5/site-packages/scipy/linalg/decomp_cholesky.py", line 30, in _cholesky
    raise LinAlgError("%d-th leading minor not positive definite" % info)
numpy.linalg.linalg.LinAlgError: 1-th leading minor not positive definite

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michaelcolaresi/Desktop/Research/SecCouncil2/ewc_fin_draft2/LIP.py", line 76, in LIP
    X = GaussianMarkovChain(np.zeros((I,D)), 1e-3*np.tile(np.identity(D),(I,1,1)), A, rho, n=N, name='X')
  File "/Users/michaelcolaresi/anaconda/envs/myBayesPyDot51/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/gaussian_markov_chain.py", line 772, in __init__
    super().__init__(mu, Lambda, A, nu, n=n, inputs=inputs, **kwargs)
  File "/Users/michaelcolaresi/anaconda/envs/myBayesPyDot51/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/expfamily.py", line 87, in constructor_decorator
    __init__(self, *args, **kwargs)
  File "/Users/michaelcolaresi/anaconda/envs/myBayesPyDot51/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/expfamily.py", line 129, in __init__
    **kwargs)
  File "/Users/michaelcolaresi/anaconda/envs/myBayesPyDot51/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/stochastic.py", line 122, in __init__
    self.initialize_from_prior()
  File "/Users/michaelcolaresi/anaconda/envs/myBayesPyDot51/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/expfamily.py", line 179, in initialize_from_prior
    self._initialize_from_parent_moments(*u_parents)
  File "/Users/michaelcolaresi/anaconda/envs/myBayesPyDot51/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/expfamily.py", line 171, in _initialize_from_parent_moments
    mask=mask)
  File "/Users/michaelcolaresi/anaconda/envs/myBayesPyDot51/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/gaussian_markov_chain.py", line 112, in compute_moments_and_cgf
    (CovXnXn, CovXpXn, Xn, ldet) = linalg.block_banded_solve(A, B, y)
  File "/Users/michaelcolaresi/anaconda/envs/myBayesPyDot51/lib/python3.5/site-packages/bayespy/utils/linalg.py", line 502, in block_banded_solve
    V[...,n+1,:,:] = chol(V[...,n+1,:,:])
  File "/Users/michaelcolaresi/anaconda/envs/myBayesPyDot51/lib/python3.5/site-packages/bayespy/utils/linalg.py", line 51, in chol
    raise Exception("Matrix not positive definite")
Exception: Matrix not positive definite

**Comment by jluttine** [comment]
Thanks for the report! I made some changes to Gaussian Markov chain nodes which broke the rotations and I thought I fixed that but apparently not. I'll create a new issue for this for easier tracking and take a look soon, I hope.

**Comment by jluttine** [comment]
Oh, it's not actually related to rotations at all, interesting.. Thanks, I'll try to fix it soon!

**Comment by colaresi** [comment]
Jaako,
Thank you for the message.
All the best,
Mike
