### ISSUE TITLE
Modelling a markov tree...

### ISSUE THREAD

**Issue by nickfyson** [bayespy/bayespy#20]
Pretty new to bayesian graphical models (and your library) so this may well be a n00b question...

I'm looking to model what I guess would be called a markov tree (not hidden, in contrast to one of the other discussions). Each node has a conditional probability table, with the likelihood of being in each state dependent on the state of the parent. In line with [the discussion here](https://github.com/bayespy/bayespy/issues/15) I can construct a hidden markov tree, but not (as I understand it) then fix the true state of any given node. Right?

If I want to take the most simplistic approach and just use the parent node in the probability array of the child, how can I use a categorical node? Is this what a gate node is for?! (I couldn't find them used anywhere in an example...)

Does that question make any sense...?!

**Comment by jluttine** [comment]
Hi, sorry for the delayed answer and thanks for the question. I'll try to write a more detailed comment on Monday or Tuesday.
It is possible to fix the true states of some nodes by observing them. For instance, using the (1) approach in the linked discussion, you could observe a node as:
```
z_10.observe(3)
```
where the observed value is the observed category index (starting from zero). You can observe all or some of the nodes.

I think the question makes sense but I didn't understand it perfectly. :) Could you elaborate what is known (a priori), what is observed and what are you aiming at learning/estimating? For instance, do you know the conditional probability transition tables? Do you observe all nodes in the tree or only some?

**Comment by nickfyson** [comment]
Hey again! Okay, I'll explain the full situation...

I'm modelling a binary markov tree (each node conditional on that of its parent), and with a conditional probability table calculated independently for each branch. The root has a prior of [0.5, 0.5] and all the leaf nodes are observed. I'm then looking to infer the most likely state for all other nodes in the network.

I have what I *think* is a correct implementation, but it's not giving me the expected results on test data, and I'm trying to work out whether this is because my tree structure is wrong, or the way I am performing my inference! I am using the observe function to fix the leaf nodes, but got confused whether this was correct (the pdf doesn't reflect the change for these nodes, right? but the moments function does...?).

So, the root node is...
```python
variables[root] = Categorical([1 - prior, prior])
```
And for all other nodes...
```python
for node in non_root_nodes:

    p = [ [p_0to0, p0to1],
            [p_1to0, p1to1] ]

    variables[node] = Mixture(parent,Categorical, p_transitions)
```
Then I observe the leaves...
```python
for leaf in leaf_nodes:
    variables[leaf].observe( value_of_leaf_node ) # value is in {0, 1}
```
And finally...
```python
inf_engine = VB(*variables.values())
inf_engine.update(repeat=update_repeats, verbose=verbose)
```
I had then been extracting the inferred values for each node using variable.pdf(1). Is that correct, despite it *not* returning the observed value for leaves...?

Thanks for any advice!

**Comment by nickfyson** [comment]
Hi again. At the risk of rudely pinching more of you time, I'm going to cheekily bump this thread. :-)

Does what I'm doing seem correct to model the situation in question? Any help hugely appreciated!

**Comment by jluttine** [comment]
Hi, sorry for the delay, I've been very busy. Thanks for bumping the thread. :)

I quickly sketched a simple complete example of what I understood you are trying to do based on your code examples:
```
import numpy as np
from bayespy.nodes import Categorical, Mixture
from bayespy.inference import VB

# Number of layers including root and leaf layers
layers = 5

prior = 0.5
p_transitions = [ [0.9, 0.1],
                  [0.1, 0.9] ]

update_repeats = 1000
verbose = True

# Observed values for leaf nodes (2**(layers-1)) leaf nodes
data = np.random.randint(0, 2, 2**(layers-1))

variables = [None] * ((2**layers)-1)

for layer in range(layers):

    # Root node
    if layer == 0:
        variables[0] = Categorical([1 - prior, prior])
    else:
        for i in range(2**layer):
            parent_index = 2**(layer-1) + int(i/2) - 1
            index = 2**layer + i - 1
            parent = variables[parent_index]
            print(layer,index,parent_index)
            variables[index] = Mixture(parent, Categorical, p_transitions)
            # Observe last layer
            if layer == layers - 1:
                variables[index].observe(data[i])

inf_engine = VB(*variables)
inf_engine.update(repeat=update_repeats, verbose=verbose)

# Print nodes
for layer in range(layers):
    layer_string = ""
    values = ["{0:.2f}".format(variables[(2**layer)+i-1].get_moments()[0][1])
              for i in range(2**layer)]
    print("Layer", layer+1)
    print(",".join(values))
```
Some comments: yes, pdf(1) is correct, another option is to get the moments vectors and pick the appropriate element from it, as in the example above. Maybe the pdf(1) is more clear. However, as you noticed, it returns an incorrect value for the leaves. I have to check whether that's a bug or why is it so. Thanks.

The parts from your implementation look correct, I think it is basically identical to the sketch I wrote. In what way it doesn't work for test data? How do you use it and for what kind of test data?

**Comment by nickfyson** [comment]
So it looks like I *am* implementing things okay, which is reassuring. (And if I understand correctly, the algorithms implemented in bayespy should definitely be able to cope with such a model (scaled to thousands of nodes), and given sufficient iterations return an exact answer...?)

My testing takes the form of raw data and final results, from a previous implementation of the approach in question (that I will be applying to new data/building upon). So my first step is to build the structure of the tree and calculate the conditional probabilities, and then run an appropriate inference algorithm to infer the most likely state of the internal nodes. I'm not getting the expected results, but I wasn't sure whether my tree or my inference was the problem.

It's now looking likely to be the tree, which is useful to know. The bug-hunting continues, but with a reduced search area...

Thanks for your help!

**Comment by jluttine** [comment]
If you can give me code to reproduce unexpected results, I could take a look. It's always possible that there are bugs in BayesPy.

BayesPy doesn't give you exact answer in this case, but a VB approximation instead. I suppose it'd be possible to implement nodes to get exact inference for arbitrary categorical Markov trees, but it requires new nodes.

Don't know how large datasets this model scales to, you just need to try. :)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
