### ISSUE TITLE
cannot import bayespy

### ISSUE THREAD

**Issue by stablum** [bayespy/bayespy#22]
Hi, as I try to import bayespy I got this error message:

```python
$ python2.7
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bayespy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bayespy/__init__.py", line 8, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/bayespy/utils/__init__.py", line 8, in <module>
    from . import misc
  File "/usr/local/lib/python2.7/dist-packages/bayespy/utils/misc.py", line 49
    def parse_command_line_arguments(mandatory_args, *optional_args_list, argv=None):
                                                                             ^
SyntaxError: invalid syntax
>>> 
```

**Comment by jluttine** [comment]
Sorry, BayesPy requires Python 3. At least Python 3.3 to be more specific (because matplotlib doesn't support 3.2).

**Comment by stablum** [comment]
ok. Is it possible to get an error message if it's imported with python 2? I am still puzzled at how i was able to succesfully install it with pip2

**Comment by jluttine** [comment]
Good idea, I'll take a look!

On October 1, 2015 4:13:35 PM EEST, "stablum@gmail.com" <notifications@github.com> wrote:
>ok. Is it possible to get an error message if it's imported with python
>2? I am still puzzled at how i was able to succesfully install it with
>pip2
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bayespy/bayespy/issues/22#issuecomment-144722597

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stablum** [comment]
something like: `assert int(sys.version.split('.')[0]) >= 3, "bayespy requires Python 3"`

**Comment by jluttine** [comment]
Yep, implemented on develop branch. Will be in the next release. Thanks for the idea.
