### ISSUE TITLE
Multiple observations for HMM

### ISSUE THREAD

**Issue by ckemere** [bayespy/bayespy#31]
Imagine that I have observed several _different length_ sequences from a HMM. 

At the moment I'm doing the below, which seems quite somewhat annoying in the case in which thousands of sequences are observed. Am I missing something?

````
Z = CategoricalMarkovChain(a0, A, states=N)
Y = Mixture(Z, Gaussian, mu_est, Lambda_est)
Y.observe(y)

Z1 = CategoricalMarkovChain(a0, A, states=N1)
Y1 = Mixture(Z1, Gaussian, mu_est, Lambda_est)
Y1.observe(y1)

Q = VB(Y, Y1, Z, Z1, mu_est, Lambda_est, A, a0)
````

**Comment by jluttine** [comment]
Yep, if they had the same length, then you could use plates. But as they have different lengths, you need to have a node for each sequence. You can of course use for loops or list comprehensions to generate a bunch of nodes.

```
Z = []
Y = []
for i in range(sequences):
    Z.append(CategoricalMarkovChain(a0, A, states=N[i]))
    Y.append(Mixture(Z[i], Gaussian, mu_est, Lambda_est))
    Y[i].observe(y[i])

nodes = Y + Z + [mu_est, Lambda_est, A, a0]
Q = VB(*nodes)
```
Something like that. Just wrote it quickly without trying, so there can be some errors. Anyway, I hope you get the idea. Is this what you were looking for?

**Comment by ckemere** [comment]
Got it. Yep. Thanks!
