### ISSUE TITLE
Random sampling broken for Multinomial

### ISSUE THREAD

**Issue by jluttine** [bayespy/bayespy#56]
```python
from bayespy import nodes
nodes.Multinomial(3, [0.1, 0.9]).random()
```

    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-28-17ed94d4f545> in <module>()
          1 from bayespy import nodes
    ----> 2 nodes.Multinomial(3, [0.1, 0.9]).random()
    

    /.../lib/python3.5/site-packages/bayespy/inference/vmp/nodes/expfamily.py in random(self)
        514         Draw a random sample from the distribution.
        515         """
    --> 516         return self._distribution.random(*(self.phi), plates=self.plates)
    

    TypeError: random() got an unexpected keyword argument 'plates'

**Comment by jluttine** [comment]
Fixed by https://github.com/bayespy/bayespy/commit/1cb17f474a6ec650c49d116ea8b1b570de6808e0

**Comment by Concomitant** [comment]
I'm running into this issue also. I've installing the development version.

The following is code from your example [here](http://www.bayespy.org/en/latest/examples/multinomial.html)

`import numpy as np
import pandas as pd
from bayespy.nodes import GaussianARD, Gamma, Categorical, Dirichlet
from bayespy import nodes
import bayespy.plot as bpplt

n_colors = 5
n_bags = 3
n_trials = 20

p_colors = nodes.Dirichlet(n_colors * [0.5], plates=(n_bags,) ).random()

bpplt.hinton(p_colors)
bpplt.pyplot.title("Orignal probability distributions of colors in the bags")
bpplt.pyplot.show()

marbles = nodes.Multinomial(n_trials, p_colors).random()
print(marbles)
`


I get this error:

`Traceback (most recent call last):
  File "nodacity.py", line 17, in <module>
    marbles = nodes.Multinomial(n_trials, p_colors).random()
  File "/usr/local/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/expfamily.py", line 516, in random
    return self._distribution.random(*(self.phi), plates=self.plates)
TypeError: random() got an unexpected keyword argument 'plates'
`

**Comment by jluttine** [comment]
Are you sure you have the latest develop branch (not master) installed? I think that issue was fixed some time ago. And I'm not able to reproduce it now. What `pip freeze | grep bayespy` shows?

**Comment by jluttine** [comment]
I think this should force the latest develop branch version:
```
pip uninstall bayespy
pip install git+https://github.com/bayespy/bayespy.git@develop
```

**Comment by Concomitant** [comment]
So `pip freeze | grep bayespy` gives me `bayespy==0.4.1.dev20160419`. I ran the command: `pip install https://github.com/bayespy/bayespy/archive/master.zip` from [here](http://www.bayespy.org/en/latest/user_guide/install.html) initially. I did the uninstall/install from git you just suggested and my code runs now 👍 :) though I am a little perplexed because `pip freeze | grep bayespy` still gives me `bayespy==0.4.1.dev20160419` which is confusing O.o

Further proof of this:

```

Daniels-MacBook-Pro:bayespy dshank$ python3 nodacity.py 
Traceback (most recent call last):
  File "nodacity.py", line 17, in <module>
    marbles = nodes.Multinomial(n_trials, p_colors).random()
  File "/usr/local/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/expfamily.py", line 516, in random
    return self._distribution.random(*(self.phi), plates=self.plates)
TypeError: random() got an unexpected keyword argument 'plates'
Daniels-MacBook-Pro:bayespy dshank$ vim nodacity.py 
Daniels-MacBook-Pro:bayespy dshank$ vim nodacity.py 
Daniels-MacBook-Pro:bayespy dshank$ pip3 freeze | grep bayespy
bayespy==0.4.1.dev20160419

```

The code runs now, so I'm pretty happy. That does seem to be a little strange though.

**Comment by Concomitant** [comment]
Thank you for the swift response!

**Comment by jluttine** [comment]
Oohps, there's old instructions in the installation link you gave. Thanks for pointing it out!

And yep, actually that pip+grep command wasn't very useful because the version number is just appended by the date of the installation.. So that definitely is a bit confusing. I wanted to have git commit ID there but I had some problems with that when I tried it long time ago. But yes, confusing, but works as it actually should..

**Comment by Concomitant** [comment]
Hey, I seem to be having a related issue going through the same example, this time with Dirichlet and involving 'plats'[sic].

code: 

```

import numpy as np
import pandas as pd
from bayespy.nodes import GaussianARD, Gamma, Categorical, Dirichlet
from bayespy import nodes
from bayespy.inference import VB
import bayespy.plot as bpplt

n_colors = 5
n_bags = 3
n_trials = 20

p_colors = nodes.Dirichlet(n_colors * [0.5], plates=(n_bags,) ).random()

bpplt.hinton(p_colors)
bpplt.pyplot.title("Orignal probability distributions of colors in the bags")
bpplt.pyplot.show()

marbles = nodes.Multinomial(n_trials, p_colors).random()
print(marbles)


theta = nodes.Dirichlet(n_colors * [0.5], plats=(n_bags,))

y = nodes.Multinomial(n_trials, theta)
y.observe(marbles)

Q = VB(y, theta)
Q.update(repeat=1000)

bpplt.hinton(theta)
bpplt.pyplot.title("Learned distribution of colors")
bpplt.pyplot.show()

```

```

  File "nodacity.py", line 22, in <module>
    theta = nodes.Dirichlet(n_colors * [0.5], plats=(n_bags,))
  File "/usr/local/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/expfamily.py", line 87, in constructor_decorator
    __init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/expfamily.py", line 129, in __init__
    **kwargs)
  File "/usr/local/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/stochastic.py", line 110, in __init__
    **kwargs)
  File "/usr/local/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/node.py", line 219, in wrapper
    return func(self, *parents, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'plats'

```

Is that a typo?

**Comment by Concomitant** [comment]
Just realized it was *my* typo. My bad!

Looking forward to trying out bayespy.

**Comment by jluttine** [comment]
The example is a Jupyter notebook so you can just use the notebook and run it without copy+pasting anything, if you want. It should be possible to run them in mybinder.org too.
