### ISSUE TITLE
Generating factor graph diagrams?

### ISSUE THREAD

**Issue by avonmoll** [bayespy/bayespy#72]
What method was used to generate the factor graph diagrams that appear in the documentation? I would like to draw one of these for a project I'm working on but don't know how to approach it (other than hand-drawing everything from scratch using PowerPoint -___-).

**Comment by jluttine** [comment]
BayesNet library for TikZ: https://github.com/jluttine/tikz-bayesnet

It works in Latex. If you want to use it in Sphinx-generated documentation, then also https://github.com/jluttine/sphinx-bayesnet.

**Comment by avonmoll** [comment]
Thanks a lot!
