### ISSUE TITLE
Categorical Mixture Model : plate error

### ISSUE THREAD

**Issue by deebuls** [bayespy/bayespy#86]
I have created a a categorical mixture model . But I am getting a plate error which I am not able to understand.
```
N = 2
D = 2
K = 10

from bayespy.nodes import Dirichlet, Categorical
import numpy as np
alpha = Dirichlet(1e-5*np.ones(K),
                    name='alpha')
Z = Categorical(alpha,
                plates=(N,),
                name='z')

beta = Dirichlet(1e-5*np.ones(D),
                 plates=(K,),
                    name='beta')

from bayespy.nodes import Mixture

Y = Mixture(Z, Categorical, beta, name='Y')
```

Data:
`
data = np.array(([0,0],[0,0]))
data.shape  # (2,2)
Y.observe(data)
`

## Error  
```
ValueError: Shape of the given array not equal to the shape of the node. 

Received shape: (2, 2, 2)
Expected shape: (2, 2)

Check plates.
```

Even though I have provided a data with (2,2) shape it says received shape as (2,2,2) .
When I send data with (2,) shape its giving no error

**Comment by jluttine** [comment]
You got this sorted out? Was there something confusing in how BayesPy behaved? Or what was the error?
