### ISSUE TITLE
Is it possible to add factors in dynamic bayesian networks?

### ISSUE THREAD

**Issue by hitalex** [bayespy/bayespy#9]
This may not be appropriate question to ask in here. If you do know somewhere else I can discuss this kind of questions, please tell me.  Thanks!

**Comment by jluttine** [comment]
This is definitely one possible place to discuss. Could you please describe the desired model or operation in a bit more detail? I don't understand what you mean exactly.

**Comment by jluttine** [comment]
Sorry for the delayed answer. BayesPy is based on directed graphs, so undirected factor graphs are a bit of a problem, as you pointed out. If you can specify he CPD between the states and the other variables that affect the states, then I might be able to tell whether it is possible to implement using BayesPy. At least one dependency structure is possible:
The state transition matrix gives the probabilities of moving from one state to another state. Usually, this state transition matrix is constant, that is, it is the same matrix at each time step. However, it is possible and relatively easy to make the state transition matrix depend on other variables. One can even have, for instance, several possible state transition matrix and anoher HMM which selects one of them to be used at each time step. Is that something you had in mind or something else?

**Comment by hitalex** [comment]
It is an interesting thought, but I am afraid it is not what I want. Perhaps my idea does not work, and I will look back at this later. Thanks!
