### ISSUE TITLE
Random sampling broken for Poisson

### ISSUE THREAD

**Issue by jachymb** [bayespy/bayespy#92]
Perhaps related to #56 ? I am using bayespy 0.5.6

    >>> p=Poisson(3)
    >>> p.random()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/expfamily.py", line 521, in random
        return self._distribution.random(*(self.phi), plates=self.plates)
    TypeError: random() got an unexpected keyword argument 'plates'

**Comment by jluttine** [comment]
Thanks for the report! It should be fixed now in `develop` branch:

`pip install git+https://github.com/bayespy/bayespy.git@develop`

(If I remember the command correctly.)

**Comment by jluttine** [comment]
Just a slight warning: I haven't used Poisson node almost at all, so if you experience any issues, please don't hesitate to report.
