### ISSUE TITLE
Install bayespy on python3 having python2 in parallel

### ISSUE THREAD

**Issue by noteven2degrees** [bayespy/bayespy#95]
Hi,

I repeatedly get the RuntimeError
`BayesPy requires Python 3. You are running Python 2`
from
`pip install bayespy`.
I have both, python 3.6.0 and python 2.7.6 installed and working nicely. How can I make bayespy setup recognize my python3? Thank you!

**Comment by jluttine** [comment]
You need to use `pip` of Python 3. `pip` may point to either Python 2 or 3. To be explicit, `pip3` probably works. At least on my system, I'm not sure how general that is.

**Comment by noteven2degrees** [comment]
Many thanks, Jaakko. I was not aware of `pip3`. The installation worked out. Looking forward to work with the algo!

**Comment by jluttine** [comment]
Ok, good to hear it worked!
